### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by pixeldesu** [spacefleet/StarShip#4]
I've seen your [boosted post](https://tootplanet.space/@InspectorCaracal/102271596495621568) on the fediverse and while I'm inclined to help out, I see a few things with the current codebase that impact future-proof code and general ease of working with it.

### No concept of dependency management/autoloading

Currently, you don't use something like [Composer](https://getcomposer.org) to manage project dependencies and autoloading of local classes. This is something crucial to PHP applications written these days.

### No routing present

Currently there is no concept of routing. Files present in `public/` are the exact entrypoints.

This should be replaced with some concept of routing, on top of a MVC approach, as also mixing PHP and HTML output is not just tough to read and work with, but can also impose some risks etc.

### Class naming needs to be improved

In the case of `Activity`, any activity based off of that class should still employ the `Activity` part in it, so `Create` would be `CreateActivity`. Outside of the initial class file where this is defined through `extends` it otherwise isn't really obvious that `Create` is related to `Activity`.

### Excessive commenting in code

First of all, this is also partly admirable, because not a lot of people consider documentation at first. 👍 	

But in some cases there are quite a few comments where they are not necessary and impact readability of the code.

As an example, let's take the fill function from the `Create` activity in `activities.php`.

```php
function fill($json_array, $wrapped=true) {
    // $wrapped indicates whether $json_array has the Create activity information wrapped around the Object being created
    // true means that it does, false means that it does not
    if ($wrapped) parent::fill($json_array);
    ...
}
```

And an adjusted version using PHPDoc formatting:

```php
/**
 * loads an activity's properties from an unserialized-JSON array into the Activity object
 * 
 * @param Array $json_array Array of unserialized Activity entries
 * @param bool $wrapped Indicates whether $json_array has the Create activity information wrapped around the object being created
 */
function fill($json_array, $wrapped = true)
{
  if ($wrapped) parent::fill($json_array);
  
  ...
}
```

Unnecessary details not really relevant to the general understanding shouldn't be added to the code inlined, and if you are describing a variable, you should do so in `@param` definitions in PHPDoc blocks! Inline comments about initializing or filling up certain information don't really add a lot to the understanding of the code.

You should use inline comments if something is off the ordinary, like an edge-case or weird protocol thing that needs explaining on why the following lines do what they do, basically!

----

In general, I would really advise you to use an already existing framework as the base for Starship. It doesn't have to be something as large as [Laravel](https://laravel.com/), but something like [Symfony](https://symfony.com/) would be a good minimum (and it's the core framework basically all PHP frameworks are based on nowadays)

This would handle the very basic structure to follow for the project and it can be advanced upon that, focusing on the ActivityPub implementation and other aspects of Starship. Writing a full on PHP application and having to maintain the whole structure on a framework level will add a layer of managing which can make or break the project.

It would also solve a lot of the problems mentioned above, and even more things, like properly handling the database using a Database Abstraction Layer and alike. Having to write all that yourself and then maintaining it will take a lot of time that could overwise be used on working on the actual project that is the ActivityPub server!

_Anyways, this is just my feedback on the current state of the project!_

**Comment by InspectorCaracal** [comment]
Thank you for your very detailed feedback! I'm going to go through each of your points here one at a time.

### Dependency management

It's both fortunate and unfortunate this is the first point, because it's a pretty important one but also means I'm starting off with a "thanks, but no" type of response. I promise, anyone reading: this *isn't* my default response.

The short version is: not using Composer (or any other dependency manager) is not one of simply not knowing about it or not knowing any better, but a deliberate decision. I feel that a significant problem with modern-day code projects is that developers are encouraged to simply import entire new libraries for relatively small conveniences, which results in bloated and inefficient code that contains far more dependencies than the project's scope should by any right require. This is the mindset which (again, in my opinion) has resulted in, as you say, something like Composer being crucial these days.

This is not to say that I don't want to use any pre-existing code libraries for anything, but by removing the convenience of something like Composer and making any libraries a manual addition, it helps to ensure that things are only added when they provide a real benefit.

### No routing present

I know, but thank you. The current HTML file is a basic early-development test tool and will be removed entirely; it is in no way expected to be developed into the actual front-end. Work on the front-end has not yet begun at all.

### Class naming

This is a very good suggestion and I'm going to take it as-is! I should have thought of it myself.

### Excessive commenting

I appreciate the information about standards in comment formatting but I think that unless someone who is actually working with the code complains about the comments (since the purpose of adding comments to one's code is so *other* people know what the code does without having to go through it all themselves), I will leave it as-is.

### Final note

I will take a look at Symfony, at least, and see if I feel if using it would be a benefit. I didn't know about it before hand, so I appreciate the link!

**Comment by pixeldesu** [comment]
I get your point about dependency management and people dropping in packages for things that can easily be written by someone themselves (and in that case they should be, of course), but, I strongly disagree with this:

> This is not to say that I don't want to use any pre-existing code libraries for anything, but by removing the convenience of something like Composer and making any libraries a manual addition, it helps to ensure that things are only added when they provide a real benefit.

Checking in source code of other libraries into your project isn't really a clean approach, especially in terms of repository size, structure etc. It also imposes that you manually have to keep dependencies up to date, always copying back the source code of something to use in case there is an update. Also not sure how well this works with licensing terms.

As a project maintainer, you at first have to review contributions anyway, so if you see people using dependencies that can be easily avoided, tell them. Like this you also improve the mindset some people might have and have an impact on changing what you loathe in modern-style development. Taking away something like dependency management for this isn't the right approach.

Also, Composer isn't just beneficial for dependencies, autoloading is a huge benefit that would take away the need to `require` single files all across places.

**Comment by joyeusenoelle** [comment]
Thank you for your input. We'll take it under consideration.

**Comment by JKingweb** [comment]
> I feel that a significant problem with modern-day code projects is that developers are encouraged to simply import entire new libraries for relatively small conveniences, which results in bloated and inefficient code that contains far more dependencies than the project's scope should by any right require. This is the mindset which (again, in my opinion) has resulted in, as you say, something like Composer being crucial these days.

I'm not sure this is a particularly accurate view of cause and effect, nor that it reflects a complete understanding of Composer's utility. One can use Composer and still have few (or even no) dependent libraries. Composer's strength is as much in managing tooling as dependencies: you can run `composer install` on a freshly cloned repository and very quickly have the correct version of PHPUnit/Behat/whatever along with whatever else is required for testing, plus whatever else is required for documentation generation, or linting, or packaging, etc. Composer will also tell you if you're missing any required PHP extensions. None of these things bloat a code-base or slow down the application at run-time. And as @pixeldesu mentioned, Composer includes a proven autoloader.

My [own application](https://code.mensbeam.com/MensBeam/arsse) uses exactly four external dependencies, all of which I weighed against the effort of writing code myself. On the other hand, my application has its own database abstraction layer, its own schema migrator, its own localization framework, its own type juggling library, its own configuration handling, its own "router" (as @pixeldesu would call it), and is naturally an expression of the MVC method (though without the V part).

I absolutely agree that dependencies should be kept few, and I am very much against using monolithic application frameworks, and using Composer implies compromise on neither.

As an aside, keeping dependent libraries and/or tooling in your repository has implications for license compliance. As your application is permissively licensed, this is something worth keeping in mind.

**Comment by InspectorCaracal** [comment]
Thank you all for your input about how I should be using Composer but please rest assured that I am not ever going to change my mind on this point. I think we all can have better uses for our time than having a futile discussion about dependency management!
